# test to make sure nox reports failures correctly
from __future__ import annotations


def test_nox() -> None:
    raise AssertionError
